### ISSUE TITLE
Dotnet Core - Azure Pipelines Build

### ISSUE THREAD

**Issue by cpyfferoen** [tunnelvisionlabs/antlr4cs#338]
There are a host of issues logged that discuss dotnet core etc. specifically #208 but...
- I cannot for the life of me determine how to get Antlr/build to work on Azure Pipelines. 
- Everything works fine w/ VS2019 on my local machine 
  - "fine" meaning, from a clean state I have to build twice.. we'll call that a non-issue for now I guess
- Or if there was a way to call MSBuild from Powershell and get it to generate the Antlr code??
  - but I can't figure that out either.. if that worked i could at least do that in a Devops Pipeline

Please help guide me?
csproj
``` xml
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFrameworks>netcoreapp3.0;netstandard2.1</TargetFrameworks>
    <NeutralLanguage>en-US</NeutralLanguage>
    <LangVersion>7.3</LangVersion>
    <Version>1.1.0-dev</Version>
    <Antlr4UseCSharpGenerator>true</Antlr4UseCSharpGenerator>
    <GeneratePackageOnBuild>True</GeneratePackageOnBuild>
    <AutoGenerateBindingRedirects>false</AutoGenerateBindingRedirects>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Antlr4" Version="4.6.6" />
    <PackageReference Include="StringTemplate4" Version="4.0.9-rc1" />
  </ItemGroup>
  <ItemGroup>
    <Antlr4 Update="NeutralTextParser\NTLexer.g4">
      <CustomToolNamespace>MagicNamespace</CustomToolNamespace>
      <Listener>False</Listener>
      <Visitor>False</Visitor>
    </Antlr4>
  </ItemGroup>
</Project>
```
azure yaml
``` yml
- task: MSBuild@1
  continueOnError: true
  displayName: 'Try MSBuild'
  inputs:
    solution: '$(project)'
    platform: $(buildPlatform)
    configuration: $(buildConfiguration)

- task: DotNetCoreCLI@2
  displayName: 'Just for fun, see if msbuild made the files..'
  inputs:
    command: 'build'
    projects: $(project)
```

**Comment by cpyfferoen** [comment]
Update - perhaps it has something to do with a fragments file - 
I do have an `import MagicFragments;` line in two Lexers, but I did not have a <Antlr4/> build task for the fragments - trying this now..

**Comment by cpyfferoen** [comment]
No combination of `<Abstract/>` `<Antlr4AbstractGrammar/>` or a host of other settings will produce, using the dotnet CLI (`dotnet build` or `dotnet msbuild`), tokens for any grammar that has an Imports in it. Possibly this is related to #111 - but as soon as I start visual studio (don't even build or click any buttons) bamm! It generates the *.tokens file for my partials, and everything works there after..

**Comment by cpyfferoen** [comment]
Workaround (aka cheating):

``` yml
- task: DotNetCoreCLI@2
  displayName: 'dotnet msbuild $(project)'
  continueOnError: true
  inputs:
    command: 'custom'
    projects: '$(project)'
    custom: 'msbuild'
    arguments: '/p:DesignTimeBuild=true /p:Configuration=$(buildConfiguration)'
# yes, the above task fails.. so build again!!!
- task: DotNetCoreCLI@2
  inputs:
    command: 'build'
    projects: '$(project)'
    arguments: '-c $(buildConfiguration)'
```
and the powershell to achieve same result
``` ps
dotnet restore
dotnet msbuild /p:DesignTimeBuild=true
dotnet build
```
